/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bernadette Pecho
 */
public class ConstantMultipleRule extends javax.swing.JFrame {

    /**
     * Creates new form Derivative
     */
    public ConstantMultipleRule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jbtnSolve = new javax.swing.JButton();
        jlblResult = new javax.swing.JLabel();
        jtxtCoefficient = new javax.swing.JTextField();
        jtxtVariable = new javax.swing.JTextField();
        jtxtExponent = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jButton1.setText("←");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        jLabel7.setFont(new java.awt.Font("ISOCPEUR", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DIFFERENCIAL CALCULUS");

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("←");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("ISOCPEUR", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("The Constant Multiple Rule");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 39));

        jbtnSolve.setBackground(new java.awt.Color(222, 255, 184));
        jbtnSolve.setFont(new java.awt.Font("ISOCTEUR", 1, 14)); // NOI18N
        jbtnSolve.setForeground(new java.awt.Color(76, 120, 20));
        jbtnSolve.setText("SOLVE");
        jbtnSolve.setBorder(null);
        jbtnSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSolveActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSolve, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 80, 30));

        jlblResult.setBackground(new java.awt.Color(204, 255, 204));
        jlblResult.setFont(new java.awt.Font("Proxy 9", 1, 18)); // NOI18N
        jlblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblResult.setBorder(null);
        getContentPane().add(jlblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 240, 48));

        jtxtCoefficient.setFont(new java.awt.Font("ISOCPEUR", 1, 18)); // NOI18N
        jtxtCoefficient.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoefficient.setToolTipText("Enter the coefficient");
        jtxtCoefficient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCoefficientActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtCoefficient, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 51, 41));

        jtxtVariable.setFont(new java.awt.Font("ISOCTEUR", 1, 18)); // NOI18N
        jtxtVariable.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVariable.setToolTipText("Enter the variable");
        jtxtVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtVariableActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtVariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 51, 41));

        jtxtExponent.setFont(new java.awt.Font("ISOCPEUR", 1, 12)); // NOI18N
        jtxtExponent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtExponent.setToolTipText("Enter the exponent");
        jtxtExponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtExponentActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtExponent, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 29, -1));

        jLabel1.setFont(new java.awt.Font("ISOCPEUR", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 120, 20));
        jLabel1.setText("d/dx");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, 53));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Group 3 (2).png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/DERIVATIVE (2).png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/POWERRULEBG (1).png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtExponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtExponentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtExponentActionPerformed

    private void jtxtCoefficientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCoefficientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCoefficientActionPerformed

    private void jbtnSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSolveActionPerformed
        int a = Integer.parseInt(jtxtCoefficient.getText());
        int n = Integer.parseInt(jtxtExponent.getText());
        
        int coefficient = a * n;
        int exponent = n - 1;
        
        String x = jtxtVariable.getText(); 
        
        if (a == 0) {
            jlblResult.setText(x + "^" + exponent);
        } else {
            jlblResult.setText(coefficient + x + "^" + exponent);
        }
        

        
    }//GEN-LAST:event_jbtnSolveActionPerformed

    private void jtxtVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtVariableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtVariableActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DiffCal jf2 = new DiffCal();
        jf2.show();

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DiffCal jf2 = new DiffCal();
        jf2.show();

        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        DiffCal jf2 = new DiffCal();
        jf2.show();

        dispose();

    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        Derivative jf2 = new Derivative();
        jf2.show();

        dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PowerRule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PowerRule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PowerRule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PowerRule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PowerRule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtnSolve;
    private javax.swing.JLabel jlblResult;
    private javax.swing.JTextField jtxtCoefficient;
    private javax.swing.JTextField jtxtExponent;
    private javax.swing.JTextField jtxtVariable;
    // End of variables declaration//GEN-END:variables
}
