/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bernadette Pecho
 */
import java.util.regex.Matcher;
import java.util.regex.Pattern;
public class integ extends javax.swing.JFrame {

    /**
     * Creates new form DISolve1
     */
    public integ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxtFunction = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jlblResult = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtnSolve1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        jButton5.setText("INTEGRAL CALCULUS");

        jButton6.setText("INTEGRAL CALCULUS");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/DISolve_Logo.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/DISolve_Logo.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("ISOCTEUR", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("DIFFERENTIAL CALCULUS");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Rectangle 2 (1).png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("ISOCTEUR", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("START");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Rectangle 1.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("ISOCPEUR", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(76, 120, 20));
        jLabel5.setText("INTEGRAL CALCULUS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BACK.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jtxtFunction.setBackground(new java.awt.Color(255, 255, 255));
        jtxtFunction.setFont(new java.awt.Font("ISOCPEUR", 1, 18)); // NOI18N
        jtxtFunction.setForeground(new java.awt.Color(0, 51, 0));
        jtxtFunction.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFunction.setToolTipText("Enter the function");
        jtxtFunction.setSelectionColor(new java.awt.Color(255, 255, 255));
        jtxtFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFunctionActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 230, 59));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("ISOCTEUR", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 0));
        jButton3.setText("SOLVE");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 95, 36));

        jlblResult.setFont(new java.awt.Font("Proxy 9", 1, 14)); // NOI18N
        jlblResult.setForeground(new java.awt.Color(0, 51, 0));
        jlblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblResult.setBorder(null);
        getContentPane().add(jlblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 270, 65));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/integsign.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 90, 60));

        jbtnSolve1.setBackground(new java.awt.Color(222, 255, 184));
        jbtnSolve1.setFont(new java.awt.Font("ISOCTEUR", 1, 12)); // NOI18N
        jbtnSolve1.setForeground(new java.awt.Color(76, 120, 20));
        jbtnSolve1.setText("FORMULA");
        jbtnSolve1.setBorder(null);
        jbtnSolve1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSolve1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSolve1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 80, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/derivativebg (1).png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        DiffCal jf2 = new DiffCal();
        jf2.show();

        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        DiffCal jf2 = new DiffCal();
        jf2.show();

        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        DISolve jf2 = new DISolve();
        jf2.show();

        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        DISolve jf2 = new DISolve();
        jf2.show();

        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jtxtFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFunctionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFunctionActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String function = jtxtFunction.getText();
        String integral = getIntegral(function);
        jlblResult.setText(integral);
    }

    private String getIntegral(String function) {
        
        double[] coefficients = new double[10];
        int[] exponents = new int[10];
        int numTerms = 0;

        Pattern pattern = Pattern.compile("(-?\\d*\\.?\\d*)x\\^(\\d+)");
        Matcher matcher = pattern.matcher(function);
        while (matcher.find()) {
        String coefficientStr = matcher.group(1);
        String exponentStr = matcher.group(2);
        double coefficient = coefficientStr.isEmpty() ? 1 : Double.parseDouble(coefficientStr);
        int exponent = Integer.parseInt(exponentStr);
        coefficients[numTerms] = coefficient;
        exponents[numTerms] = exponent;
        numTerms++;
    }

    StringBuilder integral = new StringBuilder();
    for (int i = 0; i < numTerms; i++) {
        int newNumerator = (int)coefficients[i];
        int newDenominator = exponents[i] + 1;
        if (newDenominator == 1) {
            integral.append(newNumerator);
        } else {
            integral.append("(" + newNumerator + "/" + newDenominator + ")");
        }
        if (newDenominator == 1) {
            integral.append("x");
        } else if (newDenominator > 1) {
            integral.append("x^" + (exponents[i] + 1));
        }
        if (i < numTerms - 1) {
            integral.append(" + ");
        }
    }
    
    integral.append(" + C");
    
        
        
        return integral.toString();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbtnSolve1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSolve1ActionPerformed
        IFormula jf2 = new IFormula();
        jf2.show();

        dispose();
    }//GEN-LAST:event_jbtnSolve1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DISolve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DISolve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DISolve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DISolve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DISolve().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbtnSolve1;
    private javax.swing.JLabel jlblResult;
    private javax.swing.JTextField jtxtFunction;
    // End of variables declaration//GEN-END:variables
}
