/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bernadette Pecho
 */
public class QuotientRule extends javax.swing.JFrame {

    /**
     * Creates new form Derivative
     */
    public QuotientRule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtCoefficient1 = new javax.swing.JTextField();
        jtxtVariable1 = new javax.swing.JTextField();
        jtxtExponent1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtCoefficient2 = new javax.swing.JTextField();
        jtxtVariable2 = new javax.swing.JTextField();
        jtxtExponent2 = new javax.swing.JTextField();
        jbtnSolve1 = new javax.swing.JButton();
        jlblResult = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jButton1.setText("←");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("ISOCPEUR", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("The Quotient Rule");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 39));

        jLabel5.setFont(new java.awt.Font("ISOCPEUR", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(76, 120, 20));
        jLabel5.setText("f(x)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, 53));

        jtxtCoefficient1.setFont(new java.awt.Font("ISOCPEUR", 1, 18)); // NOI18N
        jtxtCoefficient1.setForeground(new java.awt.Color(0, 0, 51));
        jtxtCoefficient1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoefficient1.setToolTipText("Enter the coefficient");
        jtxtCoefficient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCoefficient1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtCoefficient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 51, 41));

        jtxtVariable1.setFont(new java.awt.Font("ISOCPEUR", 1, 18)); // NOI18N
        jtxtVariable1.setForeground(new java.awt.Color(0, 0, 51));
        jtxtVariable1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVariable1.setToolTipText("Enter the variable");
        jtxtVariable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtVariable1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtVariable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 51, 41));

        jtxtExponent1.setFont(new java.awt.Font("ISOCPEUR", 1, 12)); // NOI18N
        jtxtExponent1.setForeground(new java.awt.Color(0, 0, 51));
        jtxtExponent1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtExponent1.setToolTipText("Enter the exponent");
        jtxtExponent1.setMinimumSize(new java.awt.Dimension(13, 23));
        jtxtExponent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtExponent1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtExponent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 23, 20));

        jLabel7.setFont(new java.awt.Font("ISOCPEUR", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(76, 120, 20));
        jLabel7.setText("g(x)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, 53));

        jtxtCoefficient2.setFont(new java.awt.Font("ISOCPEUR", 1, 18)); // NOI18N
        jtxtCoefficient2.setForeground(new java.awt.Color(0, 0, 51));
        jtxtCoefficient2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoefficient2.setToolTipText("Enter the coefficient");
        jtxtCoefficient2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCoefficient2ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtCoefficient2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 51, 41));

        jtxtVariable2.setFont(new java.awt.Font("ISOCPEUR", 1, 18)); // NOI18N
        jtxtVariable2.setForeground(new java.awt.Color(0, 0, 51));
        jtxtVariable2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVariable2.setToolTipText("Enter the variable");
        jtxtVariable2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtVariable2ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtVariable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 51, 41));

        jtxtExponent2.setFont(new java.awt.Font("ISOCPEUR", 1, 12)); // NOI18N
        jtxtExponent2.setForeground(new java.awt.Color(0, 0, 51));
        jtxtExponent2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtExponent2.setToolTipText("Enter the exponent");
        jtxtExponent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtExponent2ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtExponent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 23, 20));

        jbtnSolve1.setBackground(new java.awt.Color(222, 255, 184));
        jbtnSolve1.setFont(new java.awt.Font("ISOCTEUR", 1, 14)); // NOI18N
        jbtnSolve1.setForeground(new java.awt.Color(76, 120, 20));
        jbtnSolve1.setText("SOLVE");
        jbtnSolve1.setBorder(null);
        jbtnSolve1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSolve1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSolve1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, 73, 30));

        jlblResult.setFont(new java.awt.Font("Proxy 9", 1, 12)); // NOI18N
        jlblResult.setForeground(new java.awt.Color(0, 0, 51));
        jlblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblResult.setBorder(null);
        getContentPane().add(jlblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 290, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Group 3 (2).png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/DERIVATIVE (2).png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SUMRULEBG (1).png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtExponent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtExponent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtExponent1ActionPerformed

    private void jtxtCoefficient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCoefficient1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCoefficient1ActionPerformed

    private void jtxtVariable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtVariable1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtVariable1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DiffCal jf2 = new DiffCal();
        jf2.show();

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtCoefficient2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCoefficient2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCoefficient2ActionPerformed

    private void jtxtVariable2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtVariable2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtVariable2ActionPerformed

    private void jtxtExponent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtExponent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtExponent2ActionPerformed

    private void jbtnSolve1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSolve1ActionPerformed
        int a1 = Integer.parseInt(jtxtCoefficient1.getText());
        int n1 = Integer.parseInt(jtxtExponent1.getText());
        int a2 = Integer.parseInt(jtxtCoefficient2.getText());
        int n2 = Integer.parseInt(jtxtExponent2.getText());

        String x1 = jtxtVariable1.getText();
        String x2 = jtxtVariable2.getText(); 

        String v2 = (a2 * a2) + x2 + "^" + (n2 * 2);

        String result;
        if (x1.equals(x2)) {
            int coefficient1 = a1 * a2 * n2;
            int exponent1 = n1 + n2 - 1;
            int coefficient2 = a2 * a1 * n1;
            int exponent2 = exponent1;


            String udv = coefficient1 + x1 + "^" + exponent1;
            String vdu = coefficient2 + x2 + "^" + exponent2;

            
            result = "(" + vdu + " - " + udv + ") / " + v2;
        } else {
            
            int coefficient1 = a1 * a2 * n2;
            int exponent1 = n2 - 1;
            int coefficient2 = a2 * a1 * n1;
            int exponent2 = n1 - 1;


            String udv = coefficient1 + "(" + x1 + "^" + n1 + ")" + "(" + x2 + "^" + exponent1 + ")";
            String vdu = coefficient2 + "(" + x1 + "^" + exponent2 + ")" + "(" + x2 + "^" + n2 + ")";


            result = "(" + vdu + " - " + udv + ") / " + v2;
        }


        jlblResult.setText(result);

    }//GEN-LAST:event_jbtnSolve1ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        DiffCal jf2 = new DiffCal();
        jf2.show();

        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        Derivative jf2 = new Derivative();
        jf2.show();

        dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PowerRule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PowerRule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PowerRule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PowerRule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PowerRule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbtnSolve1;
    private javax.swing.JLabel jlblResult;
    private javax.swing.JTextField jtxtCoefficient1;
    private javax.swing.JTextField jtxtCoefficient2;
    private javax.swing.JTextField jtxtExponent1;
    private javax.swing.JTextField jtxtExponent2;
    private javax.swing.JTextField jtxtVariable1;
    private javax.swing.JTextField jtxtVariable2;
    // End of variables declaration//GEN-END:variables
}
