/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bernadette Pecho
 */
import java.util.regex.Matcher;
import java.util.regex.Pattern;
public class trancendentalDC extends javax.swing.JFrame {

    /**
     * Creates new form Derivative
     */
    public trancendentalDC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jtxtFunction = new javax.swing.JTextField();
        jlblResult = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jButton1.setText("←");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        jLabel7.setFont(new java.awt.Font("ISOCPEUR", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DIFFERENCIAL CALCULUS");

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("←");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Group 3 (1).png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, -1, -1));

        jtxtFunction.setBackground(new java.awt.Color(255, 255, 255));
        jtxtFunction.setFont(new java.awt.Font("ISOCPEUR", 1, 18)); // NOI18N
        jtxtFunction.setForeground(new java.awt.Color(0, 51, 0));
        jtxtFunction.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFunction.setToolTipText("Enter the function");
        jtxtFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFunctionActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 270, 59));

        jlblResult.setFont(new java.awt.Font("Proxy 9", 1, 14)); // NOI18N
        jlblResult.setForeground(new java.awt.Color(0, 51, 0));
        jlblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblResult.setBorder(null);
        getContentPane().add(jlblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 270, 65));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("ISOCTEUR", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 0));
        jButton3.setText("SOLVE");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 95, 36));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/derivativebg (1).png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DiffCal jf2 = new DiffCal();
        jf2.show();

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DiffCal jf2 = new DiffCal();
        jf2.show();

        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtxtFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFunctionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFunctionActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String function = jtxtFunction.getText();
        String derivative = getDerivative(function);
        jlblResult.setText(derivative);
    }

    public static String getDerivative(String function) {
        // Parse the function and extract the coefficients, variables, and trigonometric functions
        double[] coefficients = new double[10];
        String[] variables = new String[10];
        String[] trigFunctions = new String[10];
        int numTerms = 0;

        Pattern pattern = Pattern.compile("(-?\\d*\\.?\\d*)(sin|cos|tan|sec|cot|csc)\\(([a-zA-Z]+)\\)");
        Matcher matcher = pattern.matcher(function);
        while (matcher.find()) {
            String coefficientStr = matcher.group(1);
            String trigFunction = matcher.group(2);
            String variable = matcher.group(3);
            double coefficient = coefficientStr.isEmpty() ? 1 : Double.parseDouble(coefficientStr);
            coefficients[numTerms] = coefficient;
            variables[numTerms] = variable;
            trigFunctions[numTerms] = trigFunction;
            numTerms++;
        }

        // Calculate the derivative
        StringBuilder derivative = new StringBuilder();
        for (int i = 0; i < numTerms; i++) {
            if (coefficients[i] != 0) {
                double newCoefficient = coefficients[i];
                String newTrigFunction;
                if (trigFunctions[i].equals("sin")) {
                    newTrigFunction = "cos";
                    derivative.append(newCoefficient + newTrigFunction + "(" + variables[i] + ")");
                } else if (trigFunctions[i].equals("cos")) {
                    newTrigFunction = "sin";
                    derivative.append("(" + "-" +newCoefficient + newTrigFunction + "(" + variables[i] + ")"+ ")");
                } else if (trigFunctions[i].equals("tan")) {
                    newTrigFunction = "sec^2";
                    derivative.append(newCoefficient + newTrigFunction + "(" + variables[i] + ")");
                } else if (trigFunctions[i].equals("sec")) {
                    newTrigFunction = "sec * tan";
                    derivative.append(newCoefficient + newTrigFunction + "(" + variables[i] + ")");
                } else if (trigFunctions[i].equals("cot")) {
                    newTrigFunction = "csc^2";
                    derivative.append("(" + "-" +newCoefficient + newTrigFunction + "(" + variables[i] + ")"+ ")");
                } else {
                    newTrigFunction = "csc^2";
                    derivative.append("(" + "-" +newCoefficient + newTrigFunction + "(" + variables[i] + ")"+ ")");
                }
                
                if (i < numTerms - 1) {
                    derivative.append(" + ");
                }
            }
        }

        return derivative.toString();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        DiffCal jf2 = new DiffCal();
        jf2.show();

        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PowerRule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PowerRule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PowerRule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PowerRule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PowerRule().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlblResult;
    private javax.swing.JTextField jtxtFunction;
    // End of variables declaration//GEN-END:variables
}
